spring.application.name=demo

#Tomcat Server Port Setting
server.port=8090

#UTF-8 Setting
spring.servlet.filter.encoding.filter-name=encodingFilter
spring.servlet.filter.encoding.filter-class=org.springframework.web.filter.CharacterEncodingFilter
spring.servlet.filter.encoding.init-param.encoding=UTF-8
spring.servlet.filter.encoding.init-param.forceEncoding=true
spring.servlet.filter.encoding.url-pattern=/*

#DEVTOOLS SETTING
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
# LiveReload
spring.devtools.livereload.enabled=true

##DATASOURCE
##spring.datasource.url=jdbc:mysql://localhost:3306/testdb
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.datasource.username=root
##spring.datasource.password=1234
#
## JPA
## none : 사용안함  update : 수정 시 반영  create : 매번 새로 생성
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

